### ISSUE TITLE
 transcrypt -r autotest.py ImportError

### ISSUE THREAD

**Issue by hexation** [QQuick/Transcrypt#288]
http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/installation_use.html#installation  
I followed all the instructions (virtualenv installation, pip installation, installation of transcrypt with virtualenv) till part 3 - run `transcrypt -r autotest.py`.  
Then it gave me this error:  

```
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.15
Copyright (C) Geatec Engineering. License: Apache 2.0

Error: cannot run autotest.py using CPython: No module named 'attribs_by_name'
Traceback (most recent call last):
  File "/home/chair/Documents/Top/ibreak-calc/env/lib/python3.5/site-packages/transcrypt/__main__.py", line 111, in main
    exec (sourceFile.read ())
  File "<string>", line 5, in <module>
ImportError: No module named 'attribs_by_name

Aborted
```
Previously I had had other errors like:  
```Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.15
Copyright (C) Geatec Engineering. License: Apache 2.0

Error: cannot run autotest.py using CPython: No module named 'consoleprinter'
Traceback (most recent call last):
  File "/home/chair/Documents/Top/ibreak-calc/env/lib/python3.5/site-packages/transcrypt/__main__.py", line 111, in main
    exec (sourceFile.read ())
  File "<string>", line 4, in <module>
  File "/home/chair/Documents/Top/ibreak-calc/env/lib/python3.5/site-packages/arguments/__init__.py", line 23, in <module>
    from consoleprinter import abort, console, handle_ex, snake_case, get_print_yaml, console_warning, remove_escapecodes, remove_extra_indentation
ImportError: No module named 'consoleprinter

Aborted
```
However I was able to use something like `pip install consoleprinter` and the errors went away.

**Comment by hexation** [comment]
https://github.com/QQuick/Transcrypt/issues/103  
I used the solution here - https://github.com/QQuick/Transcrypt/issues/103#issuecomment-242958627  
No problem now.
