### ISSUE TITLE
Error compiling module in sibling directory

### ISSUE THREAD

**Issue by Michael-F-Ellis** [QQuick/Transcrypt#321]
Does TS require to run in the directory containing the module(s) to be compiled? Here's what happens when I try to compile a module in a sibling directory. (FWIW, the module in question doesn't have any imports.)
```
Michaels-Mac-mini:app-ace-interface mellis$ transcrypt -b -n ../modules/aceconfig.py 

Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.24
Copyright (C) Geatec Engineering. License: Apache 2.0

list index out of rangeTraceback (most recent call last):
  File "/Users/mellis/anaconda3/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 143, in __init__
    moduleMetadata = ModuleMetadata (self, self.mainModuleName)
  File "/Users/mellis/anaconda3/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 64, in __init__
    '\n\tCan\'t find any of:\n\t\t{}\n'.format ('\n\t\t'. join (searchedModulePaths))
org.transcrypt.utils.Error: <unprintable Error object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mellis/anaconda3/lib/python3.5/site-packages/transcrypt/__main__.py", line 119, in main
    compiler.Program (compilerPath, __symbols__)
  File "/Users/mellis/anaconda3/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 148, in __init__
    message = '\n\t{}'.format (str (exception))
  File "/Users/mellis/anaconda3/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/utils.py", line 124, in __str__
    result += '\n\tFile \'{}\', line {}, namely:'.format (program.importStack [-1][0] .sourcePath, self.lineNr)
IndexError: list index out of range
```
EDIT: Same error if the module is in a child directory.

Compiles w/o error if I cd to the directory containing the file.
```
Michaels-Mac-mini:app-ace-interface mellis$ cd ../modules
Michaels-Mac-mini:modules mellis$ transcrypt -b -n aceconfig.py 

Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.24
Copyright (C) Geatec Engineering. License: Apache 2.0

Saving result in: /Users/mellis/PGC-SmartTabletPlus/modules/__javascript__/aceconfig.js

Ready
```

**Comment by JdeH** [comment]
Yes, currently Transcrypt has to run in the directory where the "main module" is.
This is something that is planned to be changed, but currently not with a high priority.
How much of a hindrance this is to your development?

**Comment by Michael-F-Ellis** [comment]
Thanks, Jacques.  It's not a showstopper for me as long as sys.path is honored at compile time. If it's easy to do, I'd suggest arranging for a less cryptic error message that explains the limitation.

**Comment by JdeH** [comment]
For the occasional reader: Other modules can be in the places indicated in:

http://www.transcrypt.org/docs/html/special_facilities.html#transcrypt-s-module-mechanism

**Comment by JdeH** [comment]
Pull request #362 should have solved this.
If not feel free to reopen.

KR
J
