### ISSUE TITLE
Python 3.7 fails due to "async" being a keyword 

### ISSUE THREAD

**Issue by dozingcat** [QQuick/Transcrypt#543]
Transcrypt cannot run under Python 3.7 because `transcrypt/modules/org/transcrypt/compiler.py` has a local variable named `async`, which in 3.7 is a reserved keyword. Renaming it to `async_` appears to work, as in https://github.com/QQuick/Transcrypt/compare/master...dozingcat:master

**Comment by gareth-ib** [comment]
confirm this error still exists in latest main branch

```
$ py --version
Python 3.7.0

Traceback (most recent call last):
  File "C:\apps\python3\Scripts\transcrypt-script.py", line 11, in <module>
    load_entry_point('Transcrypt==3.6.101', 'console_scripts', 'transcrypt')()
  File "C:\apps\python3\lib\site-packages\pkg_resources\__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\apps\python3\lib\site-packages\pkg_resources\__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "C:\apps\python3\lib\site-packages\pkg_resources\__init__.py", line 2324, in load
    return self.resolve()
  File "C:\apps\python3\lib\site-packages\pkg_resources\__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\apps\python3\lib\site-packages\transcrypt\__main__.py", line 53, in <module>
    from org.transcrypt import compiler
  File "C:/apps/python3/lib/site-packages/transcrypt/modules\org\transcrypt\compiler.py", line 2300
    self.visit_FunctionDef (node, async = True)
                                      ^
SyntaxError: invalid syntax
```

**Comment by JdeH** [comment]
Thanks!
We will take this into account in Transcrypt 3.7, which will also support modules and most features of dataclasses.
Release is planned ca sep 20th

**Comment by jpic** [comment]
Thanks @Jdeh !

Keep up the great work !

**Comment by skewty** [comment]
Is Python 3.5 supported?  The setup.py seems to indicate a 3.7 requirement but looking at this issue, it would seem it should have read < 3.5.

**Comment by jpic** [comment]
@skewty did you try with current master ?
