### ISSUE TITLE
Is bootstrapping or transcrypt-ing itself possible?

### ISSUE THREAD

**Issue by aiifabbf** [QQuick/Transcrypt#601]
Just a sudden thought...Is transcrypt self-compilable or bootstrapping? I mean transcrypt itself into JavaScript.

I tried `transcrypt env/bin/transcrypt` but got the following errors
```
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.7.12
Copyright (C) Geatec Engineering. License: Apache 2.0


Saving target code in: /home/benjamin/Desktop/lab-transcrypt/env/bin/__target__/org.transcrypt.__runtime__.js
Saving minified target code in: /home/benjamin/Desktop/lab-transcrypt/env/bin/__target__/org.transcrypt.__runtime__.js

list index out of rangeTraceback (most recent call last):
  File "/home/benjamin/Desktop/lab-transcrypt/env/lib/python3.6/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 104, in __init__
    self.provide (self.mainModuleName, '__main__')
  File "/home/benjamin/Desktop/lab-transcrypt/env/lib/python3.6/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 118, in provide
    return Module (self, moduleName, __moduleName__, filter)
  File "/home/benjamin/Desktop/lab-transcrypt/env/lib/python3.6/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 127, in __init__
    self.findPaths (filter)
  File "/home/benjamin/Desktop/lab-transcrypt/env/lib/python3.6/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 312, in findPaths
    message = '\n\tImport error, can\'t find any of:\n\t\t{}\n'.format ('\n\t\t'. join (self.program.searchedModulePaths))
org.transcrypt.utils.Error: <unprintable Error object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/benjamin/Desktop/lab-transcrypt/env/lib/python3.6/site-packages/transcrypt/__main__.py", line 171, in main
    compiler.Program (transpilationDirs, __symbols__, __envir__)
  File "/home/benjamin/Desktop/lab-transcrypt/env/lib/python3.6/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 108, in __init__
    message = f'\n\t{exception}'
  File "/home/benjamin/Desktop/lab-transcrypt/env/lib/python3.6/site-packages/transcrypt/modules/org/transcrypt/utils.py", line 211, in __str__
    result += '\n\tFile \'{}\', line {}, namely:'.format (str (program.importStack [-1][0] .name), self.lineNr)
IndexError: list index out of range


Aborted
```

Would be fun if transcrypt can bootstrap itself.

**Comment by phorward** [comment]
Hello @aiifabbf,
Transcrypt is written implemented for and in Python 3, but it does not implement a full Python 3 runtime in JavaScript.Therefore, compiling Transcrypt in Transcrypt to run in the browser is not possible due to lacking of several necessary CPython built-in libraries.

**Comment by aiifabbf** [comment]
Thank you for replying @phorward .

For anyone curious about compiling any language (not just Python) to JavaScript, I found [this list of languages that compile to JS](https://github.com/jashkenas/coffeescript/wiki/List-of-languages-that-compile-to-JS) from CoffeeScript project (Transcrypt is mentioned in it too).
