### ISSUE TITLE
list index out of range error when compiling jquery demo

### ISSUE THREAD

**Issue by metaperl** [QQuick/Transcrypt#604]
In the source code located [here](https://github.com/metaperl/transcrypt-play/tree/master/2-jquery) I issued the compilation command `python -m transcrypt -b -m -n hello.py` and I got the following error about which you should note two things:

1. The error message `list index out of range` is not separated from the word `Traceback`. I.e. they are squished together as `list index out of rangeTraceback (most recent call last):`
1. for some reason the Error object was unprintable and I have no idea why the program is failing.
```
(venv-transcrypt) c:\prg\transcrypt-play\2-jquery>python -m transcrypt -b -m -n hello.py
python -m transcrypt -b -m -n hello.py

Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.7.12
Copyright (C) Geatec Engineering. License: Apache 2.0


Saving target code in: c:/prg/transcrypt-play/2-jquery/__target__/org.transcrypt.__runtime__.js

list index out of rangeTraceback (most recent call last):
  File "c:/prg/venv-transcrypt/lib/site-packages/transcrypt/modules\org\transcrypt\compiler.py", line 104, in __init__
    self.provide (self.mainModuleName, '__main__')
  File "c:/prg/venv-transcrypt/lib/site-packages/transcrypt/modules\org\transcrypt\compiler.py", line 118, in provide
    return Module (self, moduleName, __moduleName__, filter)
  File "c:/prg/venv-transcrypt/lib/site-packages/transcrypt/modules\org\transcrypt\compiler.py", line 127, in __init__
    self.findPaths (filter)
  File "c:/prg/venv-transcrypt/lib/site-packages/transcrypt/modules\org\transcrypt\compiler.py", line 312, in findPaths
    message = '\n\tImport error, can\'t find any of:\n\t\t{}\n'.format ('\n\t\t'. join (self.program.searchedModulePaths))
org.transcrypt.utils.Error: <unprintable Error object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\prg\venv-transcrypt\lib\site-packages\transcrypt\__main__.py", line 171, in main
    compiler.Program (transpilationDirs, __symbols__, __envir__)
  File "c:/prg/venv-transcrypt/lib/site-packages/transcrypt/modules\org\transcrypt\compiler.py", line 108, in __init__
    message = f'\n\t{exception}'
  File "c:/prg/venv-transcrypt/lib/site-packages/transcrypt/modules\org\transcrypt\utils.py", line 211, in __str__
    result += '\n\tFile \'{}\', line {}, namely:'.format (str (program.importStack [-1][0] .name), self.lineNr)
IndexError: list index out of range


Aborted


(venv-transcrypt) c:\prg\transcrypt-play\2-jquery>
```

**Comment by jayrogers889csa** [comment]
Hi, +1 on this - tried to run the default test after installing (transcrypt -b -c -da autotest) and received the same errors as @metaperl. Environment is OSX 10.14.2 w/ Python: 3.7.1 and Transcrypt 3.7.16. Thanks for all your work on this package!!

**Comment by notEvil** [comment]
Hi,

I got the same error message and by adding a couple of print statements where the exception is raised I found that the problem in my case was a directory with exactly the same name as the python script. Transcrypt got `graph.py` as argument, looked for `graph/__init__.py` (which doesn't exist) and decided that the python script doesn't exist. After renaming the python script, everything was fine. Hope it might help!

**Comment by ZhengyiLuo** [comment]
Still fails at `import json`. Any solutions?

**Comment by hiren1771** [comment]
Is there a workaround, fails for me on fresh install against a file with just one print statement in it.

**Comment by charlysotelo** [comment]
I too have this issue

**Comment by dayvudev** [comment]
Hi. Forgive me if this is too cliche answer, but I can see that this topic is still open and I was also struggling with this problem (using webpack)
Maybe it's an old topic, but I ran into a similar problem by accident.
I've added python file to webpack compilation (using py-loader). After running th command `npm run watch` I saw the error. U ran python script compilation manually and I saw the same error as in the content of the topic.

I edited the file: `PYTHON_PATH\Lib\site-packages\transcrypt\modules\org\transcrypt\utils.py` and commented line 212
`result += '\n\tFile \'{}\', line {}, namely:'.format (str (program.importStack [-1][0] .name), self.lineNr)`

After restarting the command, I saw another error saying that the path to my file is invalid, more precisely missing slashes (have been removed from the path).

I ran the command manually: `transcrypt -b -n -m PATH_TO_FILE` - it did not work.
I added double quotes to path and ran the command again: `transcrypt -b -n -m "PATH_TO_FILE"` - it worked.
The slashes in my file path were in the wrong direction, so I got an error and the path was solved badly.

Regards

**Comment by eevleevs** [comment]
I had a similar problem, apparently because I tried to compile a file with an extension different than py.

**Comment by bishoymaurice** [comment]
I am facing same issue.

**Comment by dewball345** [comment]
I think it could be that there are a bunch of syntax errors in the python example code, especially when it comes to spacing? Try fixing those and see if it works.
