### ISSUE TITLE
Unexpected token while running node example

### ISSUE THREAD

**Issue by supergeoff** [QQuick/Transcrypt#614]
Hello,
I try to run the nodejs example found here https://www.transcrypt.org/docs/html/installation_use.html
2.5. Compiling for node.js
And get unexpected token error on node nodejs_demo.js command:

import { AssertionError, AttributeError, BaseException, DeprecationWarning, Exception, IndexError, IterableError, KeyError, NotImplementedError, RuntimeWarning, StopIteration, UserWarning, ValueError, Warning, __JsIterator__, __PyIterator__, __Terminal__, __add__, __and__, __call__, __class__, __envir__, __eq__, __floordiv__, __ge__, __get__, __getcm__, __getitem__, __getslice__, __getsm__, __gt__, __i__, __iadd__, __iand__, __idiv__, __ijsmod__, __ilshift__, __imatmul__, __imod__, __imul__, __in__, __init__, __ior__, __ipow__, __irshift__, __isub__, __ixor__, __jsUsePyNext__, __jsmod__, __k__, __kwargtrans__, __le__, __lshift__, __lt__, __matmul__, __mergefields__, __mergekwargtrans__, __mod__, __mul__, __ne__, __neg__, __nest__, __or__, __pow__, __pragma__, __proxy__, __pyUseJsNext__, __rshift__, __setitem__, __setproperty__, __setslice__, __sort__, __specialattrib__, __sub__, __super__, __t__, __terminal__,

SyntaxError: Unexpected token {
    at new Script (vm.js:85:7)
    at createScript (vm.js:266:10)
    at Object.runInThisContext (vm.js:314:10)
    at Module._compile (internal/modules/cjs/loader.js:698:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at internal/main/run_main_module.js:21:11

Any idea?

Regards

**Comment by joecrayne** [comment]
I looked at this a bit and it seems the last commit with working nodejs support was 3c54b816.  However, to use that version, I found I needed to [patch](http://paste.debian.net/plain/1155810) a variable name to avoid the python 3 reserved word "async".

**Comment by Jongy** [comment]
See https://stackoverflow.com/a/39436580/797390 - NodeJS doesn't allow this `import` syntax by default.

I followed the instructions given in that answer and managed to run current master (https://github.com/QQuick/Transcrypt/commit/a4c7e044b352d6200e5ea3ec6000248a243dfd91) with Node 10.21 (after changing the extension to `.mjs`)
