### ISSUE TITLE
error when add type hint in class without value

### ISSUE THREAD

**Issue by KAIYOHUGO** [QQuick/Transcrypt#795]
this project is awesome! but i have some problem when use it. 

# Env

- python 3.9.5 & 3.8.10
- transcrypt 3.9.0

# code

python
```python

class a:
    b: str

```
js
```js

export var a =  __class__ ('a', [object], {
	__module__: __name__,
	b: 
});

```

error output
```
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.9.0
Copyright (C) Geatec Engineering. License: Apache 2.0


Saving target code in: /home/kaiyo/vscode/addon.py/__target__/org.transcrypt.__runtime__.js
Traceback (most recent call last):
  File "/home/kaiyo/.local/lib/python3.9/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 2028, in visit_ClassDef
    self.visit (statement.value)
  File "/home/kaiyo/.local/lib/python3.9/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 985, in visit
    super () .visit (node)
  File "/usr/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/usr/lib/python3.9/ast.py", line 411, in generic_visit
    for field, value in iter_fields(node):
  File "/usr/lib/python3.9/ast.py", line 249, in iter_fields
    for field in node._fields:
AttributeError: 'NoneType' object has no attribute '_fields'

Saving target code in: /home/kaiyo/vscode/addon.py/__target__/test.js

Ready
```

i have no idea what value b should has. in python `print(b)` will throw an error, but in js except a is null , use a.b never throw an error

**Comment by wallneradam** [comment]
@KAIYOHUGO @JennaSys  It is valid if you have a `dataclass`.

**Comment by KAIYOHUGO** [comment]
I don't really know. It's been a long time since I used this tool.
